### ISSUE TITLE
Specify license for repository

### ISSUE THREAD

**Issue by MorpheusXAUT** [dotFionn/iassure-wx#4]
Just noticed this project does not have an (obvious) license specified.

I assume that since the backend `package.json` contains the `license: "ISC"` it's an open one, however it'd be great to add a top-level `LICENSE` file to clarify the license applicable 😃

**Comment by dotFionn** [comment]
Good point, I will have to take a look at the available licenses that I believe are a good fit for the project.

Expect two weeks :D

**Comment by dotFionn** [comment]
@MorpheusXAUT @cleboo

You two are the other contributors of this project. After having a quick look, I'd like to set this projects license to AGPLv3 (see https://choosealicense.com/licenses/agpl-3.0/).

As you contributed code to this repository, I need your approval for setting this license.

Please let me know whether you support this change or if you would prefer/suggest another license.

**Comment by MorpheusXAUT** [comment]
I'm usually a MIT license kind of guy since it's less restrictive, but AGPLv3 is fine by me as well 👍

**Comment by cleboo** [comment]
Hi! 

AGPLv3 or MIT are both fine with me 👍
